# Generated by Django 4.1.4 on 2023-01-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_doctor_eventfordoctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='EventForDoctor',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
